// Autogenerated using normal simavr
// and manually tweaked
#ifndef __SIM_CORE_CONFIG_H__
#define __SIM_CORE_CONFIG_H__

#define CONFIG_SIMAVR_VERSION "v1.6"
#define CONFIG_MEGA2560 1
#define CONFIG_MEGA328 1

#endif
